#ifndef __SHM_H__
#define __SHM_H__

enum shmcmd_t
{
    SHMCMD_GET_STA = 0,
    SHMCMD_STA_CMD,
    SHMCMD_STA_SET_PSET,
    SHMCMD_STA_SET_PMODE,
    
    SHMCMD_BASE_SNAPCMD,
    SHMCMD_BASE_SETCTLREG,
    
    SHMCMD_CHAN_RESET,
    SHMCMD_CHAN_SET_DBG,
    SHMCMD_CHAN_SET_EN,

    SHMCMD_METER_CMD,
    SHMCMD_METER_SET_COMACTIVE,
    SHMCMD_METER_SET_COMACTIVP,
    SHMCMD_METER_SET_PT_MDL,
    SHMCMD_METER_SET_CT_MDL,
    SHMCMD_METER_SET_PT,
    SHMCMD_METER_SET_CT,    

    SHMCMD_AC_CMD,
    SHMCMD_AC_SET_DEV_WORK_STAT,
    SHMCMD_AC_SETCTLREG,
    SHMCMD_AC_SETCOOLSTARTTEMP,
    SHMCMD_AC_SETCOOLSTOPTEMP,

    SHMCMD_EMS_SETCTLREG,
    SHMCMD_EMS_FETCHPCURV,
    SHMCMD_EMS_NEWPCURV,
    SHMCMD_EMS_DELPCURV,
    SHMCMD_EMS_EDITPCURV,
    SHMCMD_EMS_SAVEPCURV,
    SHMCMD_EMS_LOADPCURV,

    SHMCMD_EMS_FETCHDCURV,
    SHMCMD_EMS_NEWDCURV,
    SHMCMD_EMS_DELDCURV,
    SHMCMD_EMS_EDITDCURV,
    SHMCMD_EMS_SAVEDCURV,

    SHMCMD_EMS_EDITCHGTIME,
    SHMCMD_EMS_EDITDHGTIME,

    SHMCMD_METER_SETCTLREG,

    SHMCMD_MISC_YDL,
    SHMCMD_ALARM_SET, //

    SHMCMD_MQTTC_SETCTLREG,
    SHMCMD_MQTTC_SETCTLBIN,

    SHMCMD_UPLOAD_SETCTLREG,
};

int shm_init( void );
//struct shm_t* shm_get_ptr( void );

#endif
